
package webService.clent;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SayHiService", targetNamespace = "http://webService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SayHiService {


    /**
     * 
     */
    @WebMethod(operationName = "SayHiDefault")
    @Action(input = "http://webService/SayHiService/SayHiDefaultRequest", output = "http://webService/SayHiService/SayHiDefaultResponse")
    public void sayHiDefault();

    /**
     * 
     * @param name
     */
    @WebMethod(operationName = "SayHi")
    @Action(input = "http://webService/SayHiService/SayHiRequest", output = "http://webService/SayHiService/SayHiResponse")
    public void sayHi(
        @WebParam(name = "name", partName = "name")
        String name);

    /**
     * 
     * @param clientTime
     * @return
     *     returns int
     */
    @WebMethod(operationName = "CheckTime")
    @WebResult(name = "valid", partName = "valid")
    @Action(input = "http://webService/SayHiService/CheckTimeRequest", output = "http://webService/SayHiService/CheckTimeResponse")
    public int checkTime(
        @WebParam(name = "clientTime", partName = "clientTime")
        XMLGregorianCalendar clientTime);

    /**
     * 
     * @param hello
     * @return
     *     returns testjws.clent.Hello
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService/SayHiService/updateHelloRequest", output = "http://webService/SayHiService/updateHelloResponse")
    public Hello updateHello(
        @WebParam(name = "hello", partName = "hello")
        Hello hello);

}
